### ISSUE TITLE
Add a list of reserved operation names to QIR

### ISSUE THREAD

**Issue by alan-geller** [microsoft/qsharp-language#100]
While QIR doesn't and shouldn't specify a required quantum instruction set, it is helpful to specify that certain operation *names* are reserved; that is, if a target supports an operation called CNOT, that operation has to implement a two-qubit controlled X.

Where possible, actual matrices should be provided for precision.

**Comment by alan-geller** [comment]
This web app, https://tex-image-link-generator.herokuapp.com/, is helpful for turning LaTeX into something that can be embedded into a GitHub markdown page.

**Comment by kuzminrobin** [comment]
[LaTeX/Mathematics syntax](https://en.wikibooks.org/wiki/LaTeX/Mathematics)

**Comment by alan-geller** [comment]
Since the QIR specification has moved to https://github.com/qir-alliance/qir-spec, this PR can be closed.
