### ISSUE TITLE
Resources calculation for quantum arithmetic functions

### ISSUE THREAD

**Issue by rajkk1** [microsoft/qsharp-language#121]
Hello!

I have set up and ran some basic resource estimations from [the tutorial](https://www.youtube.com/watch?v=Ps5lZ0G6zIg) for the Apply Majority algorithm on Q# Jupyter notebooks using e.g.

```
// |x1 x2 x3>|y> -> |x1 x2 x3>|y + MAJ(x1, x2, x3)>
operation ApplyMajorityUsingCNOTTransformation(x1: Qubit, x2: Qubit, x3: Qubit, y: Qubit): Unit is Adj + Ctl {
    within {
        CNOT(x2, x1);
        CNOT(x2, x3);
    } apply {
        CCNOT(x1, x3, y);
        CNOT(x2, y);
    }
}
```

```
operation UsingCNOTTTransformation() : Unit {
    use (x1, x2, x3, y) = (Qubit(), Qubit(), Qubit(), Qubit()) {
        ApplyMajorityUsingCNOTTransformation(x1, x2, x3, y);
    }
}
```

`%estimate UsingCNOTTTransformation`

I was hoping to try out the same for some quantum arithmetic functions (e.g. AddFxp, some multiplication functions, etc.) but I’m having some trouble understanding how to implement them. Are there any good resources describing how to implement a simple fixed point addition function (and count the resources?)

Thank you!

**Comment by msoeken** [comment]
Hi @rajkk1, thanks for your question. For [`AddFxP`](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.arithmetic.addfxp) you could do the following in Jupyter notebooks

```
%package Microsoft.Quantum.Numerics
```

```qsharp
open Microsoft.Quantum.Arithmetic;

operation EstimateAddFxP() : Unit {
  use a = Qubit[6];
  use b = Qubit[6];

  // fixed point representation with 4 bits before and 2 bits after the period
  use fpA = FixedPoint(4, a);
  use fpB = FixedPoint(4, b);

  // Add fpA into fpB
  AddFxP(fpA, fpB);
}
```

```
%estimate EstimateAddFxP
```

You can also find a Resources Estimation notebook for arithmetic in the Numerics package in the index of https://aka.ms/try-qsharp. The underlying sample can be found [in our Samples repository](https://github.com/microsoft/Quantum/tree/main/samples/numerics/resource-counting).

Let me know if you have further questions.

**Comment by rajkk1** [comment]
Thanks for the reply! When running `%package Microsoft.Quantum.Metrics` I obtain the output

```
Adding package Microsoft.Quantum.Numerics: done!
Microsoft.Quantum.Standard::0.20.2110171573
Microsoft.Quantum.Standard.Visualization::0.20.2110171573
Microsoft.Quantum.Numerics::0.20.2110171573
```

which seems reasonable. However when running the next block I get

```
C:\snippet_.qs(8,13): error QS3213: Invalid initializer expression. Possible initializers are "Qubit()", "Qubit[expr]", or tuples thereof.
C:\snippet_.qs(9,13): error QS3213: Invalid initializer expression. Possible initializers are "Qubit()", "Qubit[expr]", or tuples thereof.
```

Thanks for the help!

**Comment by msoeken** [comment]
@rajkk1, I had a mistake in the example code which I now fixed and also tested. I have updated my initial answer (there were two `use` statements which need to be `let` statements).

**Comment by rajkk1** [comment]
Ah neat, thank you for the change and your timely help! Works great now :)
