### ISSUE TITLE
BigInt literals now accept binary and octal formats

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-language#42]
microsoft/qsharp-compiler#673 added support for binary and octal BigInt literals to the compiler. The documentation on [BigInt Literals](https://github.com/microsoft/qsharp-language/blob/main/Specifications/Language/3_Expressions/ValueLiterals.md#bigint-literals) in the Q# specification should be updated.

**Comment by samarsha** [comment]
@ziqi-ma in case you also wanted to update the documentation. :) If not, I or someone else can get to it soon.

**Comment by ziqi-ma** [comment]
Sent in PR:)
