### ISSUE TITLE
` used in place of '

### ISSUE THREAD

**Issue by cgranade** [microsoft/qsharp-language#63]
On https://github.com/microsoft/qsharp-language/blob/main/Specifications/Language/4_TypeSystem/OperationsAndFunctions.md, the tick used to denote type parameters is written as `` ` `` instead in some places.

For instance, as rendered at https://review.docs.microsoft.com/en-us/quantum/user-guide/language/typesystem/operationsandfunctions?branch=pr-en-us-1129 (internal link):

![image](https://user-images.githubusercontent.com/31516/100293339-3c396300-2f38-11eb-8a64-2d2fe9a37de7.png)

**Comment by tcNickolas** [comment]
Looks like this has been fixed in c9d550212550?

**Comment by bettinaheim** [comment]
This is indeed fixed with the commit above.
