### ISSUE TITLE
Code sample in Iterations throws exceptions

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp-language#69]
1. `mutable results = new (Int, Results)[Length(qubits)];` should have type `Result` as the second tuple element.
2. The second loop (the one that measures the qubits) should either iterate from 0 to `Length - 1` or use `index - 1` as qubit index in the array, otherwise it throws `ArgumentOutOfRangeException`.
3. Not a bug per se, but it looks weird to allocate an empty array of the right size and then append new elements to it; it seems more common either to allocate an array of size 0 and append to it or to allocate an empty array of the right size and then overwrite its elements with measurement results.

**Comment by samarsha** [comment]
Thanks! Yeah, I agree with those issues in the example. For reference, here is [the link to the code sample](https://github.com/microsoft/qsharp-language/blob/main/Specifications/Language/2_Statements/Iterations.md).
