### ISSUE TITLE
Description lacks the limitations: __quantum__rt__array_concatenate

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-language#75]
(I'm relatively new to this code base and I may be comparing unrelated things)  

The [Data Type Representation](https://github.com/microsoft/qsharp-language/blob/main/Specifications/QIR/Data-Types.md) page does not mention that the `__quantum__rt__array_concatenate` function is only applicable for  
1-dimenstional arrays,  
in both arrays the elements must have the same size in bytes;  

whereas the implementation of 
`QirArray* quantum__rt__array_concatenate(QirArray* head, QirArray* tail)` in [`src/QirRuntime/lib/QIR/arrays.cpp`](https://github.com/microsoft/qsharp-runtime/blob/main/src/QirRuntime/lib/QIR/arrays.cpp) requires 1 dimension:  
`assert(head->dimensions == 1 && tail->dimensions == 1)`.  
It also calls `concatenated->Append(tail)` which contains:
`assert(this->itemSizeInBytes == other->itemSizeInBytes)`.

The documentation for `__quantum__rt__array_concatenate ` (in [Data Type Representation](https://github.com/microsoft/qsharp-language/blob/main/Specifications/QIR/Data-Types.md)) likely needs to mention those limitations.

**Comment by bettinaheim** [comment]
Resolved with #54.
